window.BLR_POTHOLE_SEED = {
  constituencies: [
    {
      id: "mahadevapura",
      name: "Mahadevapura",
      mla: "Manjula S",
      party: "BJP",
      zone: "East",
      wards: ["Bellandur", "Marathahalli", "Doddanekkundi"],
    },
    {
      id: "shivajinagar",
      name: "Shivajinagar",
      mla: "Rizwan Arshad",
      party: "INC",
      zone: "Central",
      wards: ["Pulikeshinagar", "Shivajinagar", "Bharathi Nagar"],
    },
    {
      id: "basavanagudi",
      name: "Basavanagudi",
      mla: "L A Ravi Subramanya",
      party: "BJP",
      zone: "South",
      wards: ["Basavanagudi", "Chamarajpet", "Gandhi Bazaar"],
    },
    {
      id: "hebbal",
      name: "Hebbal",
      mla: "B A Basavaraj",
      party: "BJP",
      zone: "North",
      wards: ["Nagawara", "Hebbal", "Sanjaynagar"],
    },
    {
      id: "sarvagnanagar",
      name: "Sarvagnanagar",
      mla: "K J George",
      party: "INC",
      zone: "East",
      wards: ["CV Raman Nagar", "Benniganahalli", "Kaggadasapura"],
    },
    {
      id: "rajarajeshwarinagar",
      name: "Rajarajeshwarinagar",
      mla: "Munirathna",
      party: "BJP",
      zone: "South-West",
      wards: ["Kengeri", "Rajarajeshwari Nagar", "Nayandahalli"],
    },
  ],
  reports: [
    {
      id: "r1",
      title: "Outer Ring Road near Bellandur flyover",
      description: "Broken stretch after rain with repeated bike skids during peak traffic.",
      constituencyId: "mahadevapura",
      severity: "critical",
      status: "open",
      lat: 12.9315,
      lng: 77.6784,
      createdAt: "2026-04-12",
    },
    {
      id: "r2",
      title: "Marathahalli bridge service road",
      description: "Wide crater close to bus stop forcing autos into the main lane.",
      constituencyId: "mahadevapura",
      severity: "high",
      status: "in-progress",
      lat: 12.9591,
      lng: 77.6974,
      createdAt: "2026-04-10",
    },
    {
      id: "r3",
      title: "Queens Road junction",
      description: "Uneven resurfacing and deep trench making night travel unsafe.",
      constituencyId: "shivajinagar",
      severity: "high",
      status: "open",
      lat: 12.9852,
      lng: 77.6031,
      createdAt: "2026-04-11",
    },
    {
      id: "r4",
      title: "Commercial Street back road",
      description: "Multiple small potholes merged into a broken patch near drain covers.",
      constituencyId: "shivajinagar",
      severity: "medium",
      status: "fixed",
      lat: 12.9834,
      lng: 77.6098,
      createdAt: "2026-04-05",
    },
    {
      id: "r5",
      title: "NR Colony main road",
      description: "Road edge collapsed near school, very risky for morning drop-offs.",
      constituencyId: "basavanagudi",
      severity: "critical",
      status: "open",
      lat: 12.9389,
      lng: 77.5668,
      createdAt: "2026-04-09",
    },
    {
      id: "r6",
      title: "Hebbal underpass approach",
      description: "Series of potholes collecting water and slowing all lanes.",
      constituencyId: "hebbal",
      severity: "high",
      status: "open",
      lat: 13.0352,
      lng: 77.597,
      createdAt: "2026-04-14",
    },
    {
      id: "r7",
      title: "Nagawara ring road slip lane",
      description: "Sharp-edged road damage hidden under puddles after evening rain.",
      constituencyId: "hebbal",
      severity: "medium",
      status: "in-progress",
      lat: 13.0415,
      lng: 77.6206,
      createdAt: "2026-04-13",
    },
    {
      id: "r8",
      title: "Kaggadasapura main street",
      description: "Badly broken patch near apartment entrance with heavy school traffic.",
      constituencyId: "sarvagnanagar",
      severity: "high",
      status: "open",
      lat: 12.9721,
      lng: 77.6717,
      createdAt: "2026-04-15",
    },
    {
      id: "r9",
      title: "Old Airport Road service lane",
      description: "Repeated trenching left rough, unsafe edges for two-wheelers.",
      constituencyId: "sarvagnanagar",
      severity: "medium",
      status: "open",
      lat: 12.9696,
      lng: 77.6495,
      createdAt: "2026-04-08",
    },
    {
      id: "r10",
      title: "Kengeri satellite town circle",
      description: "Damaged surface near signal causing buses to slow abruptly.",
      constituencyId: "rajarajeshwarinagar",
      severity: "medium",
      status: "fixed",
      lat: 12.9144,
      lng: 77.4821,
      createdAt: "2026-04-03",
    },
  ],
};
